name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKERHUBUSER: ${{secrets.DOCKERHUBUSER}}
        DOCKERHUBPASSWORD: ${{secrets.DOCKERHUBPASSWORD}}
      run: | 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag olsonjac/bio_web_app:$(date +%s)
        docker login -u $DOCKERHUBUSER -p $DOCKERHUBPASSWORD
    - name: Docker Push
      run: docker push olsonjac/bio_web_app
